//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvisoReabastecimentoEstoque.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServiceAvisoReabastecimentoEntities : DbContext
    {
        public ServiceAvisoReabastecimentoEntities()
            : base("name=ServiceAvisoReabastecimentoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvisoReabastecimento> AvisoReabastecimento { get; set; }
        public virtual DbSet<EmailAuto> EmailAuto { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<vw_PendenteAviso> vw_PendenteAviso { get; set; }
    }
}
