//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvisoReabastecimentoEstoque.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto()
        {
            this.AvisoReabastecimento = new HashSet<AvisoReabastecimento>();
        }
    
        public string ProCodigo { get; set; }
        public string ProdNome { get; set; }
        public bool ProAvisaRessup { get; set; }
        public int ProQtdEstoque { get; set; }
        public int ProQtdAvisa { get; set; }
        public int ProQtdAviso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvisoReabastecimento> AvisoReabastecimento { get; set; }
    }
}
